# Gitleaks configuration for solution-desk-engine
# Exclude test files that intentionally contain patterns for negative testing

[allowlist]
paths = [
    "tests/test_hardcoded_detection.py",
]

regexes = [
    '''api_key.*=.*"hardcoded-fallback"''',
]

description = "Test files containing intentional security anti-patterns for detection testing"
