repos:
  # Branch protection - prevents commits to main branch
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      # CRITICAL: Block direct commits to main branch
      - id: no-commit-to-branch
        args: ['--branch', 'main', '--branch', 'master']
        name: 🔒 Main branch protection
        description: |
          Direct commits to main/master branches are blocked for safety.

          To commit your changes:
          1. Create a feature branch: git checkout -b feature/your-change
          2. Make your commits on the feature branch
          3. Use pull requests to merge to main

          This protects the main branch from accidental commits.

      # Essential file validation
      - id: check-yaml
        exclude: ^(docker-compose\.yml|\.github/workflows/|modules/.*\.yaml|monitoring/.*\.yaml|deploy/.*\.yml)
      - id: check-json
      - id: check-merge-conflict
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-ast
        files: \.py$
      - id: forbid-new-submodules
      - id: check-executables-have-shebangs
        files: \.(py|sh|bash)$
      - id: fix-byte-order-marker
      - id: check-added-large-files
        args: ['--maxkb=1000']
      - id: detect-private-key

  # TODO/FIXME/HACK detection - prevents placeholder code from reaching main
  - repo: local
    hooks:
      - id: no-todos
        name: Block TODO/FIXME/HACK items
        description: Prevents TODO, FIXME, and HACK comments from being committed
        entry: bash -c 'for file in "$@"; do if grep -E "(TODO|FIXME|HACK|XXX)" "$file" > /dev/null 2>&1; then echo "❌ Found TODO/FIXME/HACK items in $file. Please resolve before committing."; grep -n -E "(TODO|FIXME|HACK|XXX)" "$file"; exit 1; fi; done' --
        language: system
        files: \.(py|ts|tsx|js|jsx|go|tf)$
        exclude: "test.*|.*_test\\.(py|ts|tsx|js|jsx|go)$|\\.git/|node_modules/|\\.venv/|\\.next/|dist/|build/|__pycache__/"

  # Essential security - secret detection
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.28.0
    hooks:
      - id: gitleaks

  # Python specific hooks
  - repo: https://github.com/psf/black
    rev: 24.10.0
    hooks:
      - id: black
        language_version: python3.11

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

# Global settings
default_language_version:
  python: python3.11

# Exclude patterns
exclude: |
  (?x)^(
    \.git/.*|
    \.devcontainer/.*|
    \.vscode/.*|
    \.idea/.*|
    build/.*|
    tmp/.*|
    \.venv/.*|
    venv/.*|
    __pycache__/.*|
    \.pytest_cache/.*|
    \.mypy_cache/.*|
    htmlcov/.*|
    .*\.bak|
    .*\.backup|
    .*-backup-.*
  )$

# Stop on first failure to avoid running unnecessary checks
fail_fast: true
